[package]
authors = ["Jan Nils Ferner <jn_ferner@hotmail.de>"]
name = "chapter_three"
version = "0.1.0"
edition = "2021"

[dependencies]
byteorder = "1.4.3"
flate2 = "1.0.22"
glob = "0.3.0"
walkdir = "2.3.2"
