[package]
name = "chapter_five"
version = "0.1.0"
authors = ["Jan Nils Ferner <jn_ferner@hotmail.de>"]
edition = "2021"

[dependencies]
lazy_static = "1.4"
regex = "1.5"
bitflags = "1.3"
chapter-five-derive = { path = "chapter-five-derive" }
