[package]
name = "chapter-five-derive"
version = "0.1.0"
authors = ["Jan Nils Ferner <jn_ferner@hotmail.de>"]
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = "1.0.82"
quote = "1.0.10"
