[package]
authors = ["Jan Nils Ferner"]
name = "chapter_four"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.1.6"
serde = "1.0.130"
serde_derive = "1.0.130"
serde_json = "1.0.72"
toml = "0.5.8"
